[build]
  command = "npm run build"
  publish = "dist"

[dev]
  port = 8889
  targetPort = 5173

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/venues"
  to = "/.netlify/functions/api-venues-list"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


