INSERT INTO venues260414 (
  id,
  destination_slug,
  category,
  name,
  slug,
  status,
  live,
  stars,
  reviews,
  excerpt,
  description,
  lat,
  lng,
  map_url,
  instagram,
  image,
  source,
  created_by,
  updated_by
)
VALUES
  (
    'casa-tikiri',
    'ahangama',
    'stays',
    'Casa Tikiri Boutique Hotel',
    'casa-tikiri',
    'active',
    TRUE,
    4.9,
    286,
    'An adults only boutique hideaway blending authentic Italian soul with tropical surf.',
    'An adults only boutique hideaway blending authentic Italian soul with tropical surf.',
    5.9818709,
    80.3467529,
    'https://maps.app.goo.gl/rQJa2yj5y4XbdWXP8',
    'casatikiri',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786339766/Casa_Tikiri_02_oe9tj4.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'kai-rooftop',
    'ahangama',
    'eat',
    'Kai Rooftop',
    'kai-rooftop',
    'active',
    TRUE,
    4.6,
    1657,
    'Rooftop dining, great cocktails and beautiful ocean views.',
    'Rooftop dining, great cocktails and beautiful ocean views.',
    5.9723502,
    80.3635430,
    'https://maps.app.goo.gl/eRRmfHJ7uq3ry5VZ7',
    'kai_ahangama',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426785/Kai_rooftop_ahangama_mcetbs.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'mermaids-kitchen',
    'ahangama',
    'eat',
    'Mermaid''s Kitchen',
    'mermaids-kitchen',
    'active',
    TRUE,
    4.6,
    750,
    'Fresh, flavourful food served in a relaxed tropical setting.',
    'Fresh, flavourful food served in a relaxed tropical setting.',
    5.9702466,
    80.3672881,
    'https://maps.app.goo.gl/e8BqTHRCjGfq9CDE7',
    'mermaids_kitchen_ahangama',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786427902/Mermaids_cbow9y.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'lamana-ahangama',
    'ahangama',
    'eat',
    'Lamana',
    'lamana-ahangama',
    'active',
    TRUE,
    4.4,
    336,
    'A popular late-night hangout with a lively atmosphere, great music, and a skate rink that adds a playful twist to the night.',
    'A popular late-night hangout with a lively atmosphere, great music, and a skate rink that adds a playful twist to the night.',
    5.9723738,
    80.3639983,
    'https://maps.app.goo.gl/jAMYSH9VbaigtUVP7',
    'lamana_ahangama',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786620612/Lamana_23_vnrlgv.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'mono-ahangama',
    'ahangama',
    'eat',
    'MONO',
    'mono-ahangama',
    'active',
    TRUE,
    5,
    13,
    'Modern nightlife with a retro soul, creative cocktails, quality drinks, and timeless tunes that keep the night moving.',
    'Modern nightlife with a retro soul, creative cocktails, quality drinks, and timeless tunes that keep the night moving.',
    5.9725588,
    80.3635790,
    'https://maps.app.goo.gl/hyL2QCdzD6oZWCEt6',
    'find_mono_',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426470/mono3_c0p2jh.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'kicks-ahangama',
    'ahangama',
    'eat',
    'Kicks Ahangama',
    'kicks-ahangama',
    'active',
    TRUE,
    4.5,
    53,
    'Dance, socialise and enjoy the night.',
    'Dance, socialise and enjoy the night.',
    5.9723763,
    80.3639558,
    'https://maps.app.goo.gl/ZZcd5BL6RnGqE9xK6',
    'kicks_ahangama',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786344638/Kicks_Ahangama_bkuzuq.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'hotel-de-uncles',
    'ahangama',
    'eat',
    'Hotel De Uncle''s',
    'hotel-de-uncles',
    'active',
    TRUE,
    4.7,
    372,
    'A laid-back seaside favourite for golden sunsets, chilled drinks, live bands, and unforgettable evenings by the ocean.',
    'A laid-back seaside favourite for golden sunsets, chilled drinks, live bands, and unforgettable evenings by the ocean.',
    5.9723415,
    80.3633269,
    'https://maps.app.goo.gl/cpP7BNhzC4bi6pH69',
    'hoteldeuncles',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426468/Uncle_2_c3vkpl.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'mint-ceylon',
    'ahangama',
    'retail',
    'Mint Ceylon',
    'mint-ceylon',
    'active',
    TRUE,
    4.7,
    0,
    'Consciously crafted slow fashion and unique lifestyle pieces, mindfully handmade by local artisans in the heart of Sri Lanka.',
    'Consciously crafted slow fashion and unique lifestyle pieces, mindfully handmade by local artisans in the heart of Sri Lanka.',
    5.973834393620351,
    80.36327069432797,
    'https://maps.app.goo.gl/DgphUYpCcKj7AJsf7',
    'mint.ceylon',
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787289095/mint_ceylong_axzbft.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  ),
  (
    'ak-bike-rentals',
    'ahangama',
    'transport',
    'AK Bike Rentals',
    'ak-bike-rentals',
    'active',
    TRUE,
    5,
    21,
    'Top-rated scooter rentals and easy local movement around Ahangama.',
    'Top-rated scooter rentals and easy local movement around Ahangama.',
    NULL,
    NULL,
    'https://maps.app.goo.gl/4i3vmix5xRGhJYzh9',
    NULL,
    'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787570539/AK_bike_rental_1_jajy1y.webp',
    'guide-2026-09',
    'guide-venue-seed',
    'guide-venue-seed'
  )
ON CONFLICT DO NOTHING;