-- Guide Venues table: stores all venues shown on the /guide page
CREATE TABLE IF NOT EXISTS guide_venues (
  id            TEXT PRIMARY KEY,
  section       TEXT NOT NULL,           -- e.g. best_stays, best_eats, best_cafes, etc.
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL,
  description   TEXT,
  image         TEXT,
  lat           DOUBLE PRECISION,
  lng           DOUBLE PRECISION,
  instagram     TEXT,
  google_maps   TEXT,
  website       TEXT,
  rating        DOUBLE PRECISION,
  review_count  INTEGER DEFAULT 0,
  google_place_id TEXT,
  ownership     TEXT,                    -- 'local' or 'foreign'
  tagline       TEXT,
  priority_order INTEGER DEFAULT 0,     -- ordering within section
  status        TEXT DEFAULT 'active',  -- active, draft, archived
  deleted_at    TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_guide_venues_section ON guide_venues(section);
CREATE INDEX IF NOT EXISTS idx_guide_venues_status ON guide_venues(status);
CREATE UNIQUE INDEX IF NOT EXISTS idx_guide_venues_slug ON guide_venues(slug);

-- Guide Content table: stores editable text content for guide sections
CREATE TABLE IF NOT EXISTS guide_content (
  section_key   TEXT PRIMARY KEY,        -- e.g. overview, best_season, how_long, transport, closing
  title         TEXT,
  body          TEXT,
  image         TEXT,
  updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Seed default content rows
INSERT INTO guide_content (section_key, title, body) VALUES
  ('overview', 'Overview', 'Ahangama is a laid-back coastal town on Sri Lanka''s southern surf belt, home to world-class waves, tropical cafés, and a growing community of creatives, surfers, and slow-livers.'),
  ('best_season', 'Best Season', 'The undisputed prime time to visit is late October through April. During these months, the weather is hot and sunny (averaging around 29°C to 31°C), the rainfall is minimal, and the ocean is calm and glassy, creating pristine surfing conditions.'),
  ('how_long', 'How Long Do People Usually Stay?', 'Vacationers typically carve out 5 to 10 days to soak up the surf and food scene. However, because of the infectious "slow living" rhythm, digital nomads and slow-travelers frequently end up extending their stays for 1 to 3 months.'),
  ('transport_getting_here', 'Getting Here', 'Ahangama is around a 2–3 hour drive from Bandaranaike International Airport (CMB), depending on traffic and your exact destination. Private airport transfers are the most convenient option, with prices varying depending on the vehicle and provider. The train is a beautifully scenic and budget-friendly alternative, but expect a longer journey and additional connections from the airport.'),
  ('transport_getting_around', 'Getting Around', 'Renting a scooter is one of the best ways to explore Ahangama and the surrounding coast, with local rentals often starting at around LKR 2,000 per day. Local tuk-tuks are also widely available for shorter journeys—just agree on the price before getting in, or use a ride-hailing app where available.')
ON CONFLICT (section_key) DO NOTHING;

-- Seed existing hardcoded venues into the guide_venues table
INSERT INTO guide_venues (id, section, name, slug, description, image, lat, lng, instagram, google_maps, website, rating, review_count, ownership, priority_order, status) VALUES
-- Best Stays
('ko-lake-villa', 'best_stays', 'Ko Lake Villa', 'ko-lake-villa', 'A private seven-bedroom lakeside villa made for slow days, sunset gatherings and unforgettable stays in Ahangama.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787639927/Ko_Lake_Villa_2_i7p3nr.webp', 5.9845509, 80.3373084, 'https://www.instagram.com/kolakevilla.ahangama/', 'https://maps.app.goo.gl/qryXBvviUDxXwrcMA', 'https://www.kolakevilla.com/', 4.4, 23, 'foreign', 1, 'active'),
('mugatiya', 'best_stays', 'The Mugatiya Ahangama Luxury Heritage Villa', 'mugatiya', 'A private garden retreat in Ahangama, blending the intimacy of a home with the beauty of tropical island living.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787640178/Mugatiya_shycdl.webp', 5.9845509, 80.3373084, 'https://www.instagram.com/villamugatiya/', 'https://maps.app.goo.gl/WqfdmS5YvF4X1hPQA', 'https://mugatiya.com/', 4.7, 43, 'foreign', 2, 'active'),
('sisters-kabalana', 'best_stays', 'Sisters Kabalana', 'sisters-kabalana', 'Relaxed island stays with the warmth of home, thoughtfully cared for by our team of local women.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788161176/Sisters_Acc_copy_g55nt7.webp', 5.9779099, 80.3513977, 'https://www.instagram.com/sisterssrilanka/', 'https://maps.app.goo.gl/sZkg9p6iZmcYv6rA8', 'https://sisterssrilanka.com/', 4.9, 288, 'local', 3, 'active'),
('casa-samaya', 'best_stays', 'Casa Samaya', 'casa-samaya', 'Where body, heart and spirit align.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788749420/Casa_Samaya_rdbpjv.webp', 5.973244991042889, 80.43546070822997, 'https://www.instagram.com/casasamaya/', 'https://maps.app.goo.gl/b4xJ7nWBZwoG2oUk8', 'https://casasamaya.com/', 4.9, 191, NULL, 4, 'active'),
('villa-alba', 'best_stays', 'Villa Alba', 'villa-alba', 'Conceived and styled largely as a private home, Villa Alba Ahangama has smoothly switched to cute boutique hotel. Don''t miss our in room massages overlooking the paddy fields.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788327862/Alba_d29yn3.webp', 6.004850003281442, 80.34979863779847, 'https://www.instagram.com/villaalba_srilanka/', 'https://maps.app.goo.gl/A7hiQF3axmk3drLb9', 'https://www.villaalbaahangama.com/', 4.9, 114, 'foreign', 5, 'active'),
('pebble-alma', 'best_stays', 'Pebble Alma', 'pebble-alma', 'A minimalist, container-style eco-pod retreat offering couples a secluded private garden oasis in the heart of Ahangama.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788408665/pebble_alma_kzzjtc.webp', 5.975776677693355, 80.3636174782393, 'https://www.instagram.com/pebble.alma/', 'https://maps.app.goo.gl/uYPWvoxNo4rsM79x5', NULL, 3.7, 10, NULL, 6, 'active'),
('ebb-flow', 'best_stays', 'Ebb & Flow Jungalows', 'ebb-flow', 'A staffed, beachfront boutique retreat offering laid-back luxury and private pools just steps from Midigama''s premier surf breaks.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788409318/ebb_and_flow_jatgto.webp', 5.963341091581912, 80.39707773963637, 'https://www.instagram.com/ebbandflowjungalows/', 'https://maps.app.goo.gl/HDdWtK6Sse5jrjqy6', 'https://ebbandflowjungalows.com/', 4.6, 41, NULL, 7, 'active'),
('surf-club', 'best_stays', 'Surf Club Midigama', 'surf-club', 'A vibrant beachfront pool club and fusion restaurant in Southern Sri Lanka, blending chic poolside lounging with curated sunset DJ sets and ocean-inspired dining.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788411397/surfclub_iycmcx.webp', 5.964028072439051, 80.3929395039731, 'https://www.instagram.com/surfclubmidigama/', 'https://maps.app.goo.gl/em45fSbqsYBqBv8HA', 'https://surfclubmidigama.com/', 5.0, 13, NULL, 8, 'active'),
('younger-villas', 'best_stays', 'Younger Villas & Resorts', 'younger-villas', 'A serene four-star sanctuary in Ahangama blending modern luxury, exceptional hospitality, and tranquil coastal charm.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788410351/younger_villa_ca6lce.webp', 5.980023716891554, 80.37545424019842, 'https://www.instagram.com/youngervillas/', 'https://maps.app.goo.gl/uc4F3nC7kMsCxqhF8', NULL, 4.9, 134, NULL, 9, 'active'),
('animals', 'best_stays', 'Animals', 'animals', 'A sleek pink boutique oasis blending premium co-working and laid back surf culture for adult travelers.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1784783052/colorred_animals_oj6aee.webp', 5.979034944715787, 80.3542700558208, 'https://www.instagram.com/animalsahangama/', 'https://maps.app.goo.gl/YwNuhDw4sC6MiBpw9', NULL, 4.8, 137, NULL, 10, 'active'),
('lighthouse', 'best_stays', 'Lighthouse', 'lighthouse', 'A beautiful beachfront escape with a rooftop spot to enjoy sunsets, good food, and great coastal vibes.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1782832527/light-house-beach-view-hero_mzhrhn.webp', 5.965762, 80.377438, 'https://www.instagram.com/lighthouse_ahangama/', 'https://maps.app.goo.gl/qi4E2nWnjq3M9pQP9', 'https://www.lighthouseahangama.com/', 4.7, 517, 'foreign', 11, 'active'),
('trebartha', 'best_stays', 'Trebartha East – The Roundhouse', 'trebartha', 'An architectural retreat amidst a cinnamon plantation.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786339767/Threbatha_East_01_yb2dwm.webp', 5.997323316318728, 80.35726862935918, 'https://www.instagram.com/trebarthaeast/', 'https://maps.app.goo.gl/QMpJ6AvyxnnJv2jy7', 'https://trebartha-east.com/', 4.9, 101, 'foreign', 12, 'active'),
('benison', 'best_stays', 'The Benison', 'benison', 'A hidden retreat designed for slow living.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786339767/The_Benison_02_uzlcpb.webp', 5.9749308289716305, 80.37235731469872, 'https://www.instagram.com/thebenison_ahangama/', 'https://maps.app.goo.gl/Pm2h4n6Gr9cr94PA9', 'https://thebenisonhotels.com/', 4.9, 121, 'local', 13, 'active'),
('casa-tikiri', 'best_stays', 'Casa Tikiri Boutique Hotel', 'casa-tikiri', 'An adults only boutique hideaway blending authentic Italian soul with tropical surf.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786339766/Casa_Tikiri_02_oe9tj4.webp', 5.9818709, 80.3467529, 'https://www.instagram.com/casatikiri/', 'https://maps.app.goo.gl/rQJa2yj5y4XbdWXP8', 'https://www.casatikiri.com/', 4.9, 286, 'foreign', 14, 'active'),

-- Best Eats
('citra', 'best_eats', 'Citra', 'citra', 'A Culinary Experience Nestled Between The Palm Trees And The Ocean.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787500275/main_pic_g5ftha.webp', 5.9730175, 80.4349573, 'https://www.instagram.com/citrasrilanka', 'https://maps.app.goo.gl/Nompp9W4szZurLdr8', 'https://www.citra-restaurant.com/', 4.6, 655, 'local', 1, 'active'),
('ribs', 'best_eats', 'RIBS', 'ribs', 'Smokin'' Hot', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787647988/RIBS_guqhau.webp', 5.972562, 80.363215, 'https://www.instagram.com/ribsahangama', 'https://maps.app.goo.gl/example', NULL, 4.5, 77, NULL, 2, 'active'),
('oyummy', 'best_eats', 'Oyummy', 'oyummy', 'Lush garden eatery blending Lebanese soul food with tropical surf vibes.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160859/Oyummy_gyml2q.webp', 5.971984, 80.364521, 'https://www.instagram.com/oyummy_ahangama', 'https://maps.app.goo.gl/example', NULL, 4.8, 190, NULL, 3, 'active'),
('samba', 'best_eats', 'Samba Ahangama', 'samba', 'Beachside slow-living sanctuary with dining and co-working.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160858/Samba_mjepvr.webp', 5.970542, 80.365873, 'https://www.instagram.com/sambaahangama', 'https://maps.app.goo.gl/example', NULL, 4.8, 327, NULL, 4, 'active'),
('taboo', 'best_eats', 'Taboo Beach Club', 'taboo', 'Upscale boho-chic oasis with beach parties and luxury dining.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160857/Taboo_k7qx6y.webp', 5.969871, 80.367125, 'https://www.instagram.com/tablobaloochclub', 'https://maps.app.goo.gl/example', NULL, 5.0, 17, NULL, 5, 'active'),
('kai-rooftop', 'best_eats', 'Kai Rooftop', 'kai-rooftop', 'Rooftop dining, great cocktails and beautiful ocean views.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426785/Kai_rooftop_ahangama_mcetbs.webp', 5.9723502, 80.3635430, 'https://www.instagram.com/kai_ahangama', 'https://maps.app.goo.gl/eRRmfHJ7uq3ry5VZ7', NULL, 4.6, 1657, NULL, 6, 'active'),
('mermaids', 'best_eats', 'Mermaid''s Kitchen', 'mermaids-kitchen', 'Fresh, flavourful food served in a relaxed tropical setting.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786427902/Mermaids_cbow9y.webp', 5.9702466, 80.3672881, 'https://www.instagram.com/mermaids_kitchen_ahangama', 'https://maps.app.goo.gl/e8BqTHRCjGfq9CDE7', NULL, 4.6, 750, NULL, 7, 'active'),
('pickled-pelican', 'best_eats', 'Pickled Pelican', 'pickled-pelican', 'Creative dishes, refreshing drinks and relaxed coastal atmosphere.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160856/Pickled_pelican_wqjb4e.webp', 5.968934, 80.368291, 'https://www.instagram.com/pickledpelican', 'https://maps.app.goo.gl/example', NULL, 4.4, 208, NULL, 8, 'active'),

-- Best Cafes
('kaffi', 'best_cafes', 'Kaffi Ahangama', 'kaffi', 'Brews & Bakes To Save The Day', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1784779727/Kaffi946318185961736_7826978568551728722_n_Topaz_Gigapixel_4x_scale_iz1aop.webp', 5.972891, 80.363145, 'https://www.instagram.com/kaffi.ahangama', 'https://maps.app.goo.gl/example', NULL, 4.7, 389, NULL, 1, 'active'),
('aliikai', 'best_cafes', 'Aliikai Cafe', 'aliikai', 'A cosy beachside cafe serving wholesome bowls, artisan coffee and tropical vibes.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160855/Aliikai_ijbxtq.webp', 5.971234, 80.364567, 'https://www.instagram.com/aliikaicafe', 'https://maps.app.goo.gl/example', NULL, 4.9, 176, NULL, 2, 'active'),
('sisters-cafe', 'best_cafes', 'Sisters Cafe', 'sisters-cafe', 'Mediterranean flavours with an island twist, exceptional coffee, by local women.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160854/Sisters_cafe_qz3r7y.webp', 5.970567, 80.365234, 'https://www.instagram.com/sisterssrilanka', 'https://maps.app.goo.gl/example', NULL, 4.9, 288, 'local', 3, 'active'),
('cafe-samaya', 'best_cafes', 'Café Samaya', 'cafe-samaya', 'Connecting through flavours.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160853/Cafe_samaya_bnm4k8.webp', 5.969891, 80.365901, 'https://www.instagram.com/cafesamaya', 'https://maps.app.goo.gl/example', NULL, 4.9, 467, NULL, 4, 'active'),
('thilenis', 'best_cafes', 'Thileni''s', 'thilenis', 'Vibrant beachfront cafe and sunset lounge with surf views and coastal fusion cuisine.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160852/Thilenis_jk4m9n.webp', 5.969218, 80.366568, 'https://www.instagram.com/thilenis', 'https://maps.app.goo.gl/example', NULL, 4.6, 1116, NULL, 5, 'active'),
('daily-dose', 'best_cafes', 'Daily Dose', 'daily-dose', 'Laid-back coastal cafe with specialty matcha, local bites, and workspace vibes.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160851/Daily_dose_lk9p3m.webp', 5.968545, 80.367235, 'https://www.instagram.com/dailydoseahangama', 'https://maps.app.goo.gl/example', NULL, 5.0, 64, NULL, 6, 'active'),
('living-room', 'best_cafes', 'Living Room Concept Store', 'living-room', 'Curated Turkish/Sri Lankan designer boutique blended with a cafe.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160850/Living_room_p5r2qz.webp', 5.967872, 80.367902, 'https://www.instagram.com/livingroomconceptstore', 'https://maps.app.goo.gl/example', NULL, 4.9, 102, NULL, 7, 'active'),
('cafe-ceylon', 'best_cafes', 'Cafe Ceylon', 'cafe-ceylon', 'Rustic cafe blending Ceylon tea traditions with modern cafe culture.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160849/Cafe_ceylon_t6m8kl.webp', 5.967199, 80.368569, 'https://www.instagram.com/cafeceylon', 'https://maps.app.goo.gl/example', NULL, 4.3, 431, NULL, 8, 'active'),
('petals', 'best_cafes', 'Petals', 'petals', 'Floral-themed cafe with artisan lattes, fresh pastries, and peaceful garden atmosphere.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160848/Petals_u3m7kl.webp', 5.966526, 80.369236, 'https://www.instagram.com/petalsahangama', 'https://maps.app.goo.gl/example', NULL, 5.0, 201, NULL, 9, 'active'),
('cafe-wave', 'best_cafes', 'Cafe Wave', 'cafe-wave', 'Breezy roadside cafe with fresh juices, light bites, and surf-town vibe.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160847/Cafe_wave_x7k2mn.webp', 5.965853, 80.369903, 'https://www.instagram.com/cafawave', 'https://maps.app.goo.gl/example', NULL, 4.8, 209, NULL, 10, 'active'),
('abrazo', 'best_cafes', 'Abrazo', 'abrazo', 'Spanish-inspired cafe serving tapas-style bites, specialty coffee, and warm coastal hospitality.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160846/Abrazo_n8m3kl.webp', 5.965180, 80.370570, 'https://www.instagram.com/abrazoahangama', 'https://maps.app.goo.gl/example', NULL, 4.8, 756, NULL, 11, 'active'),
('crave', 'best_cafes', 'Crave', 'crave', 'Popular local cafe known for flavour-packed brunches, fresh smoothies, and vibrant atmosphere.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160845/Crave_m9k3pl.webp', 5.964507, 80.371237, 'https://www.instagram.com/craveahangama', 'https://maps.app.goo.gl/example', NULL, 4.8, 223, NULL, 12, 'active'),

-- Best Experiences
('kumbuk', 'best_experiences', 'Kumbuk Kitchen & Art Space', 'kumbuk', 'Hands-on Sri Lankan cooking classes in a creative setting.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160844/Kumbuk_a7m3kl.webp', 5.971234, 80.364567, 'https://www.instagram.com/kumbukkitchen', 'https://maps.app.goo.gl/example', NULL, 5.0, 53, NULL, 1, 'active'),
('coconut-court', 'best_experiences', 'Coconut Court Pickleball', 'coconut-court', 'Fastest growing sport in a fun and social setting.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160843/Coconut_court_p5m2kl.webp', 5.970567, 80.365234, 'https://www.instagram.com/coconutcourtpickleball', 'https://maps.app.goo.gl/example', NULL, 5.0, 67, NULL, 2, 'active'),
('pachcha', 'best_experiences', 'Pachcha Sanni', 'pachcha', 'Creative tattoo studio specialising in custom designs.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160842/Pachcha_m8n3kl.webp', 5.969891, 80.365901, 'https://www.instagram.com/pachchasanni', 'https://maps.app.goo.gl/example', NULL, 5.0, 3, NULL, 3, 'active'),
('qamar', 'best_experiences', 'Qamar by Zan', 'qamar', 'Design and create your own jewellery in hands-on workshops.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160841/Qamar_l9m3kl.webp', 5.969218, 80.366568, 'https://www.instagram.com/qamarbyzan', 'https://maps.app.goo.gl/example', NULL, 5.0, 16, NULL, 4, 'active'),
('jn-tattoo', 'best_experiences', 'JN Tattoo', 'jn-tattoo', 'Clean, top-rated studio specialising in custom fine-line tattoos.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160840/JN_tattoo_m8n3kl.webp', 5.968545, 80.367235, 'https://www.instagram.com/jntattoo', 'https://maps.app.goo.gl/example', NULL, 5.0, 8, NULL, 5, 'active'),

-- Wellness
('crossfit', 'wellness', 'CrossFit Ceylon Palm gym', 'crossfit', NULL, 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160839/Crossfit_m8n3kl.webp', 5.971234, 80.364567, 'https://www.instagram.com/crossfitceylonpalm', 'https://maps.app.goo.gl/example', NULL, 5.0, 25, NULL, 1, 'active'),
('calma', 'wellness', 'Calma Samaya', 'calma', 'Sanctuary for inner balance.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160838/Calma_l9m3kl.webp', 5.970567, 80.365234, 'https://www.instagram.com/calmasamaya', 'https://maps.app.goo.gl/example', NULL, 5.0, 72, NULL, 2, 'active'),
('pura-pilates', 'wellness', 'Pura Pilates', 'pura-pilates', 'Welcoming Pilates studio for strength, balance, and well-being.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160837/Pura_m8n3kl.webp', 5.969891, 80.365901, 'https://www.instagram.com/purapilates', 'https://maps.app.goo.gl/example', NULL, 4.9, 189, NULL, 3, 'active'),
('white-lotus', 'wellness', 'White Lotus Spa – Radisson Collection', 'white-lotus', 'Luxury spa treatments to relax, restore, and rejuvenate.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160836/White_lotus_l9m3kl.webp', 5.969218, 80.366568, 'https://www.instagram.com/whitelotusspa', 'https://maps.app.goo.gl/example', NULL, 4.9, 116, NULL, 4, 'active'),
('banya', 'wellness', 'Banya Steam House', 'banya', 'Hot steam, cold plunges and deep relaxation.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160835/Banya_m8n3kl.webp', 5.968545, 80.367235, 'https://www.instagram.com/banyasteamhouse', 'https://maps.app.goo.gl/example', NULL, 5.0, 58, NULL, 5, 'active'),
('nuga-house', 'wellness', 'The Nuga House', 'nuga-house', 'Tranquil sanctuary for rest and healing.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160834/Nuga_l9m3kl.webp', 5.967872, 80.367902, 'https://www.instagram.com/thenugahouse', 'https://maps.app.goo.gl/example', NULL, 4.5, 161, NULL, 6, 'active'),
('sellam', 'wellness', 'Sellam Gym Ahangama', 'sellam', 'Modern gym for keeping your routine on track.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160833/Sellam_m8n3kl.webp', 5.967199, 80.368569, 'https://www.instagram.com/sellamgym', 'https://maps.app.goo.gl/example', NULL, 4.9, 50, NULL, 7, 'active'),
('spa-station', 'wellness', 'Spa Station Midigama', 'spa-station', 'Relaxing massages and rejuvenating treatments.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160832/Spa_station_l9m3kl.webp', 5.966526, 80.369236, 'https://www.instagram.com/spastationmidigama', 'https://maps.app.goo.gl/example', NULL, 4.8, 246, NULL, 8, 'active'),

-- Night Life
('lamana', 'night_life', 'Lamana', 'lamana', 'A popular late-night hangout with a lively atmosphere, great music, and a skate rink that adds a playful twist to the night.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786620612/Lamana_23_vnrlgv.webp', 5.9723738, 80.3639983, 'https://www.instagram.com/lamana_ahangama', 'https://maps.app.goo.gl/jAMYSH9VbaigtUVP7', NULL, 4.4, 336, NULL, 1, 'active'),
('hakuna', 'night_life', 'Hakuna Matata', 'hakuna', 'Beachfront cocktails, music and DJs.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1784779729/Hakuna_ColoredImage_ji8d1dji8d1dji8d_Topaz_Gigapixel_2x_scale_bxi6wt.webp', 5.971542, 80.364891, 'https://www.instagram.com/hakunamatataahangama', 'https://maps.app.goo.gl/example', NULL, 4.6, 703, NULL, 2, 'active'),
('mono', 'night_life', 'MONO', 'mono', 'Modern nightlife with a retro soul, creative cocktails, quality drinks, and timeless tunes that keep the night moving.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426470/mono3_c0p2jh.webp', 5.9725588, 80.3635790, 'https://www.instagram.com/find_mono_', 'https://maps.app.goo.gl/hyL2QCdzD6oZWCEt6', NULL, 5.0, 13, NULL, 3, 'active'),
('kurundu', 'night_life', 'Kurundu', 'kurundu', 'Lively setting for drinks and evening entertainment.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160831/Kurundu_m8n3kl.webp', 5.970726, 80.365558, 'https://www.instagram.com/kurunduahangama', 'https://maps.app.goo.gl/example', NULL, 4.8, 306, NULL, 4, 'active'),
('kicks', 'night_life', 'Kicks Ahangama', 'kicks', 'Dance, socialise and enjoy the night.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786344638/Kicks_Ahangama_bkuzuq.webp', 5.9723763, 80.3639558, 'https://www.instagram.com/kicks_ahangama', 'https://maps.app.goo.gl/ZZcd5BL6RnGqE9xK6', NULL, 4.5, 53, NULL, 5, 'active'),
('hotel-de-uncles', 'night_life', 'Hotel De Uncle''s', 'hotel-de-uncles', 'A laid-back seaside favourite for golden sunsets, chilled drinks, live bands, and unforgettable evenings by the ocean.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1786426468/Uncle_2_c3vkpl.webp', 5.9723415, 80.3633269, 'https://www.instagram.com/hoteldeuncles', 'https://maps.app.goo.gl/cpP7BNhzC4bi6pH69', NULL, 4.7, 372, NULL, 6, 'active'),

-- Best Retail Stores
('gusta', 'best_retail_stores', 'Gusta', 'gusta', 'Gourmet groceries, fresh produce and artisan products.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160830/Gusta_m8n3kl.webp', 5.972109, 80.364012, 'https://www.instagram.com/gustaahangama', 'https://maps.app.goo.gl/example', NULL, 4.6, 31, NULL, 1, 'active'),
('mudra', 'best_retail_stores', 'Mudra Herbal Spicy Tea Shop', 'mudra', 'Handcrafted teas, local spices and Sri Lankan flavours.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160829/Mudra_l9m3kl.webp', 5.971436, 80.364679, 'https://www.instagram.com/mudraherbaltea', 'https://maps.app.goo.gl/example', NULL, 4.9, 37, NULL, 2, 'active'),
('mint-ceylon', 'best_retail_stores', 'Mint Ceylon', 'mint-ceylon', 'Consciously crafted slow fashion and unique lifestyle pieces, mindfully handmade by local artisans in the heart of Sri Lanka.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787289095/mint_ceylong_axzbft.webp', 5.973834393620351, 80.36327069432797, 'https://www.instagram.com/mint.ceylon', 'https://maps.app.goo.gl/DgphUYpCcKj7AJsf7', NULL, 4.7, 0, NULL, 3, 'active'),
('yiva', 'best_retail_stores', 'Yiva Essentials', 'yiva', 'Fashion, lifestyle, and unique finds.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160828/Yiva_m8n3kl.webp', 5.970763, 80.365346, 'https://www.instagram.com/yivaessentials', 'https://maps.app.goo.gl/example', NULL, 5.0, 13, NULL, 4, 'active'),
('prickly-pear', 'best_retail_stores', 'Prickly Pear by Cactus', 'prickly-pear', 'Colorful beachfront concept boutique with resort style and cafe vibes.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160827/Prickly_pear_l9m3kl.webp', 5.970090, 80.366013, 'https://www.instagram.com/pricklypearbycactus', 'https://maps.app.goo.gl/example', NULL, 3.8, 21, NULL, 5, 'active'),

-- Transport
('ak-bike', 'transport', 'AK Bike Rentals', 'ak-bike', 'Top-rated scooter rentals and easy local movement around Ahangama.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1787570539/AK_bike_rental_1_jajy1y.webp', NULL, NULL, NULL, 'https://maps.app.goo.gl/4i3vmix5xRGhJYzh9', NULL, 5.0, 21, NULL, 1, 'active'),
('spring-tours', 'transport', 'Spring Tours', 'spring-tours', 'Premier private transport and custom island itineraries.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160826/Spring_tours_m8n3kl.webp', NULL, NULL, 'https://www.instagram.com/springtours', 'https://maps.app.goo.gl/example', NULL, 5.0, 45, NULL, 2, 'active'),
('scooty-rental', 'transport', 'Scooty Rental & Taxi Service', 'scooty-rental', 'Quick scooter access and local transport.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160825/Scooty_l9m3kl.webp', NULL, NULL, NULL, 'https://maps.app.goo.gl/example', NULL, 5.0, 497, NULL, 3, 'active'),
('happy-tours', 'transport', 'Happy Tours', 'happy-tours', 'Practical transport partner for local trips.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160824/Happy_tours_m8n3kl.webp', NULL, NULL, NULL, 'https://maps.app.goo.gl/example', NULL, 5.0, 134, NULL, 4, 'active'),
('nova-rent', 'transport', 'Nova Rent a Car', 'nova-rent', 'Cars and transport for exploring beyond Ahangama.', 'https://res.cloudinary.com/dp7in4ulw/image/upload/v1788160823/Nova_l9m3kl.webp', NULL, NULL, NULL, 'https://maps.app.goo.gl/example', NULL, 4.8, 39, NULL, 5, 'active')
ON CONFLICT (id) DO NOTHING;
