INSERT INTO guide_venue_placements (
  venue_id,
  section,
  priority_order,
  name_override,
  tagline
)
VALUES
  ('ko-lake', 'best_stays', 1, 'Ko Lake Villa', NULL),
  ('villa-mugatiya', 'best_stays', 2, 'The Mugatiya Ahangama Luxury Heritage Villa', NULL),
  ('sisters-away', 'best_stays', 3, NULL, NULL),
  ('casa-samaya', 'best_stays', 4, NULL, NULL),
  ('villa-alba', 'best_stays', 5, NULL, NULL),
  ('pebble-alma', 'best_stays', 6, NULL, NULL),
  ('ebb-and-flow-jungalows', 'best_stays', 7, 'Ebb & Flow Jungalows', NULL),
  ('surf-club', 'best_stays', 8, 'Surf Club Midigama', NULL),
  ('younger-villas-resorts', 'best_stays', 9, NULL, NULL),
  ('animals', 'best_stays', 10, NULL, NULL),
  ('lighthouse', 'best_stays', 11, NULL, NULL),
  ('trebartha-east-the-roundhouse', 'best_stays', 12, NULL, NULL),
  ('the-benison-ahangama', 'best_stays', 13, NULL, NULL),
  ('casa-tikiri', 'best_stays', 14, NULL, NULL),
  ('citra-ahangama', 'best_eats', 1, NULL, NULL),
  ('ribs', 'best_eats', 2, 'RIBS', NULL),
  ('terra-resort', 'best_eats', 3, NULL, NULL),
  ('coco-kitchen', 'best_eats', 4, 'Coco Kitchen', NULL),
  ('oyummy', 'best_eats', 5, NULL, NULL),
  ('samba-ahangama', 'best_eats', 6, 'Samba Ahangama', NULL),
  ('taboo-beach-club', 'best_eats', 7, NULL, NULL),
  ('kai-rooftop', 'best_eats', 8, NULL, NULL),
  ('mermaids-kitchen', 'best_eats', 9, 'Mermaid’s Kitchen', NULL),
  ('pickled-pelican', 'best_eats', 10, NULL, NULL),
  ('nirbana-retreat', 'best_experiences', 1, 'Nirbana Retreat Paddle Boarding', NULL),
  ('kumbuk-community', 'best_experiences', 2, 'Kumbuk Kitchen & Art Space', NULL),
  ('coconut-court', 'best_experiences', 3, 'Coconut Court Pickleball', NULL),
  ('pachcha-sanni', 'best_experiences', 4, NULL, NULL),
  ('qamar-by-zan', 'best_experiences', 5, NULL, NULL),
  ('jn-tattoo-sri-lanka', 'best_experiences', 6, 'JN Tattoo', NULL),
  ('crossfit-ceylon-palm-gym', 'wellness', 1, NULL, NULL),
  ('calma-samaya', 'wellness', 2, NULL, NULL),
  ('nirbana-retreat', 'wellness', 3, NULL, NULL),
  ('terra-resort', 'wellness', 4, NULL, NULL),
  ('pura-pilates-ahangama', 'wellness', 5, NULL, NULL),
  ('white-lotus-spa-wellness', 'wellness', 6, 'White Lotus Spa – Radisson Collection', NULL),
  ('banya-steam-house', 'wellness', 7, NULL, NULL),
  ('the-nuga-house', 'wellness', 8, NULL, NULL),
  ('sellam', 'wellness', 9, 'Sellam Gym Ahangama', NULL),
  ('spa-station-midigama', 'wellness', 10, NULL, NULL),
  ('lamana-ahangama', 'night_life', 1, NULL, NULL),
  ('hakuna-matata-ahangama', 'night_life', 2, NULL, NULL),
  ('mono-ahangama', 'night_life', 3, NULL, NULL),
  ('kurundu-ahangama', 'night_life', 4, 'Kurundu', NULL),
  ('kicks-ahangama', 'night_life', 5, NULL, NULL),
  ('hotel-de-uncles', 'night_life', 6, 'Hotel De Uncle’s', NULL),
  ('azure-swim', 'best_retail_stores', 1, NULL, NULL),
  ('gusta', 'best_retail_stores', 2, NULL, NULL),
  ('mudra-herbal-spicy-tea-shop', 'best_retail_stores', 3, NULL, NULL),
  ('mint-ceylon', 'best_retail_stores', 4, NULL, NULL),
  ('yiva-essentials', 'best_retail_stores', 5, NULL, NULL),
  ('cactus-ahangama', 'best_retail_stores', 6, 'Prickly Pear by Cactus', NULL),
  ('kaffi-ahangama', 'best_cafes', 1, 'Kaffi Ahangama', NULL),
  ('aliikai-ahangama', 'best_cafes', 2, 'Aliikai Cafe', 'Local Woman-Owned'),
  ('sisters-kabalana', 'best_cafes', 3, 'Sisters Cafe', NULL),
  ('caf-samaya', 'best_cafes', 4, NULL, NULL),
  ('thilenis', 'best_cafes', 5, NULL, NULL),
  ('daily-dose-cafe', 'best_cafes', 6, 'Daily Dose', NULL),
  ('living-room-concept-store', 'best_cafes', 7, NULL, NULL),
  ('cafe-ceylon-ahangama', 'best_cafes', 8, 'Cafe Ceylon', NULL),
  ('patels-ahangama', 'best_cafes', 9, NULL, NULL),
  ('cafe-wave', 'best_cafes', 10, NULL, NULL),
  ('abrazo-ahangama', 'best_cafes', 11, 'Abrazo', NULL),
  ('crave', 'best_cafes', 12, NULL, NULL),
  ('ashen-surf-school', 'surf_schools', 1, NULL, NULL),
  ('ak-bike-rentals', 'transport', 1, NULL, NULL),
  ('spring-tours', 'transport', 2, NULL, NULL),
  ('scooty-rental-and-taxi-service', 'transport', 3, NULL, NULL),
  ('happy-tours', 'transport', 4, NULL, NULL),
  ('nova-rent-a-car', 'transport', 5, NULL, NULL)
ON CONFLICT (guide_key, venue_id, section) DO UPDATE SET
  priority_order = EXCLUDED.priority_order,
  name_override = EXCLUDED.name_override,
  tagline = EXCLUDED.tagline,
  updated_at = NOW();

UPDATE venues260414 AS venue
SET
  website = COALESCE(metadata.website, venue.website),
  ownership = COALESCE(metadata.ownership, venue.ownership),
  updated_at = NOW()
FROM (VALUES
  ('ko-lake', 'https://www.kolakevilla.com/', 'foreign'),
  ('villa-mugatiya', 'https://mugatiya.com/', 'foreign'),
  ('sisters-away', 'https://sisterssrilanka.com/', 'local'),
  ('casa-samaya', 'https://casasamaya.com/', NULL),
  ('villa-alba', 'https://www.villaalbaahangama.com/', 'foreign'),
  ('ebb-and-flow-jungalows', 'https://ebbandflowjungalows.com/', NULL),
  ('surf-club', 'https://surfclubmidigama.com/', NULL),
  ('lighthouse', 'https://www.lighthouseahangama.com/', 'foreign'),
  ('trebartha-east-the-roundhouse', 'https://trebartha-east.com/', 'foreign'),
  ('the-benison-ahangama', 'https://thebenisonhotels.com/', 'local'),
  ('casa-tikiri', 'https://www.casatikiri.com/', 'foreign'),
  ('citra-ahangama', 'https://www.citra-restaurant.com/', 'local'),
  ('ribs', NULL, 'local'),
  ('terra-resort', 'https://www.terraresortsl.com/', NULL),
  ('coco-kitchen', 'https://cocokitchencollections.com/', NULL),
  ('taboo-beach-club', 'https://www.taboobeachclub.com.mx/', NULL),
  ('kai-rooftop', NULL, 'foreign'),
  ('mermaids-kitchen', NULL, 'local'),
  ('pickled-pelican', NULL, 'foreign'),
  ('nirbana-retreat', 'https://www.nirbanaretreat.com/', NULL),
  ('kumbuk-community', NULL, 'local'),
  ('coconut-court', 'https://coconutcourt.setmore.com/', 'local'),
  ('pachcha-sanni', NULL, 'foreign'),
  ('qamar-by-zan', NULL, 'foreign'),
  ('jn-tattoo-sri-lanka', NULL, 'local'),
  ('crossfit-ceylon-palm-gym', 'https://crossfitceylon.com/', NULL),
  ('calma-samaya', 'https://www.casasamaya.com/wellness.html', 'local'),
  ('pura-pilates-ahangama', 'https://purapilatessrilanka.com/', 'local'),
  ('white-lotus-spa-wellness', 'https://whitelotusgalle.com/', 'foreign'),
  ('banya-steam-house', NULL, 'local'),
  ('the-nuga-house', 'https://www.thenugahouse.com/', 'local'),
  ('sellam', NULL, 'local'),
  ('spa-station-midigama', NULL, 'local'),
  ('lamana-ahangama', NULL, 'foreign'),
  ('hakuna-matata-ahangama', NULL, 'foreign'),
  ('mono-ahangama', NULL, 'foreign'),
  ('kurundu-ahangama', 'https://kurundurestaurant.com/', 'local'),
  ('kicks-ahangama', 'https://kicks.easyweek.io/', 'foreign'),
  ('hotel-de-uncles', 'https://unclescolombo.lk/', 'local'),
  ('gusta', 'https://www.gusta.lk/', 'local'),
  ('mudra-herbal-spicy-tea-shop', NULL, 'local'),
  ('mint-ceylon', 'https://mintceylon.com/', 'local'),
  ('yiva-essentials', NULL, 'foreign'),
  ('cactus-ahangama', NULL, 'foreign'),
  ('kaffi-ahangama', NULL, 'local'),
  ('aliikai-ahangama', NULL, 'local'),
  ('sisters-kabalana', 'https://sisterssrilanka.com/', 'local'),
  ('caf-samaya', 'https://casasamaya.com/restaurant.html', NULL),
  ('cafe-ceylon-ahangama', 'https://www.cafeceylon.lk/', 'local'),
  ('ashen-surf-school', 'https://ashensurfschool.com/', NULL),
  ('ak-bike-rentals', NULL, 'local'),
  ('scooty-rental-and-taxi-service', NULL, 'local'),
  ('happy-tours', NULL, 'foreign'),
  ('nova-rent-a-car', NULL, 'foreign')
) AS metadata(venue_id, website, ownership)
WHERE venue.id = metadata.venue_id;